language: node_js
node_js:
    - "stable"
    - "4.0"
    - "0.12"
    - "0.10"
services:
    - mongodb
    - rabbitmq
before_script:
    - sleep 10
script:
    - npm test
after_success:
    - npm run coveralls
