language: node_js
node_js:
    - "stable"
    - "5.0"
    - "4.2"
    - "0.12"
    - "0.10"
services:
#    - mongodb #mongo 2.4
    - rabbitmq
    - mysql
sudo: false
addons: #installs mongo 3
  apt:
    sources:
      - mongodb-upstart 
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell      
before_script:
  - sleep 15
  
script:
    - npm test
after_success:
    - npm run coveralls
