language: node_js
node_js:
    - "stable"
    - "4.2.1"
    - "4.1"
    - "4.0"
    - "0.12"
    - "0.11"
    - "0.10"
services:
    - mongodb
before_script:
    - sleep 5
script:
    - npm install && npm test
after_success:
    - npm run coveralls
